# Generated by Django 4.1 on 2023-01-29 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_event_eventimage_order_userinformation_delete_events_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventimage',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.eventimage'),
        ),
        migrations.AddField(
            model_name='eventimage',
            name='title',
            field=models.CharField(default='Default Title', max_length=100),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(upload_to='static\\images'),
        ),
    ]
