# Generated by Django 4.1 on 2023-01-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
